### ISSUE TITLE
UIE信息抽取

### ISSUE THREAD

**Issue by xxm1668** [HarderThenHarder/transformers_tasks#32]
结果没有你写的那么高，只有F1值只有70%左右

**Comment by limefilter** [comment]
在运行UIE模型的train.py文件的时候出现了以下报错：
Traceback (most recent call last):
  File "/tmp/pycharm_project_244/UIE/train.py", line 328, in <module>
    train()
  File "/tmp/pycharm_project_244/UIE/train.py", line 249, in train
    model = torch.load(os.path.join(args.pretrained_model, 'pytorch_model.bin'))        # 加载预训练好的UIE模型，模型结构见：model.UIE()
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 777, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.


请问博主用的是什么pytorch版本？

**Comment by White-bbb** [comment]
我也是这个情况

**Comment by keyilizzie** [comment]
+1  求解答
